# fly.toml app configuration file generated for infrastreet-api on 2026-04-29T23:00:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'infrastreet-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
