#!/usr/bin/env python3
"""Generate seed_nyc_100_more.sql: 25 vendors + 100 flash deals. No media_url (NULL only)."""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "seed_nyc_100_more.sql"

ITEMS = {
    "mexican": [
        ("Tacos al pastor (3)", 13.0, 9.0),
        ("Quesadilla de chorizo", 11.0, 7.5),
        ("Elote callejero", 6.0, 4.0),
        ("Churros con chocolate", 8.0, 5.5),
    ],
    "chinese": [
        ("Soup dumplings (8)", 14.0, 9.5),
        ("Dan dan noodles", 12.0, 8.5),
        ("Scallion pancake", 7.0, 4.5),
        ("Pork bao (2)", 9.0, 6.0),
    ],
    "italian": [
        ("Margherita slice combo", 8.0, 5.5),
        ("Chicken parm wedge", 14.0, 10.0),
        ("Arancini trio", 11.0, 8.0),
        ("Tiramisu slice", 7.0, 5.0),
    ],
    "colombian": [
        ("Bandeja paisa", 18.0, 13.0),
        ("Arepa con queso", 8.0, 5.5),
        ("Empanadas (3)", 10.0, 7.0),
        ("Ajiaco grande", 16.0, 11.5),
    ],
}

# (idx, vendor_name, phone_last4, lng, lat, pickup_area, cuisine)
VENDORS = [
    (11, "La Esquina Michoacana", 1101, -73.9565, 40.7081, "Williamsburg, Brooklyn", "mexican"),
    (12, "Szechuan Spark Dumplings", 1102, -73.9234, 40.7621, "Astoria, Queens", "chinese"),
    (13, "Nonna Rita Slice Shop", 1103, -73.9912, 40.7153, "Lower East Side, Manhattan", "italian"),
    (14, "Bogotá Street Kitchen", 1104, -73.8927, 40.7475, "Jackson Heights, Queens", "colombian"),
    (15, "Oaxaca On The Go", 1105, -73.9192, 40.6948, "Bushwick, Brooklyn", "mexican"),
    (16, "Lanzhou Noodle Lab", 1106, -73.8301, 40.7614, "Flushing, Queens", "chinese"),
    (17, "Cucina da Marco", 1107, -73.9442, 40.6681, "Crown Heights, Brooklyn", "italian"),
    (18, "Medellín Arepa Club", 1108, -73.9489, 40.7445, "Long Island City, Queens", "colombian"),
    (19, "Taquería El Camión", 1109, -73.9843, 40.7264, "East Village, Manhattan", "mexican"),
    (20, "Shanghai Bites Window", 1110, -74.0105, 40.6456, "Sunset Park, Brooklyn", "chinese"),
    (21, "Nonna Brooklyn Heights", 1111, -73.9969, 40.6965, "Brooklyn Heights, Brooklyn", "italian"),
    (22, "Cali Empanadas Express", 1112, -73.8772, 40.7282, "Corona, Queens", "colombian"),
    (23, "Puebla Tacos y Más", 1113, -73.9503, 40.6782, "Greenpoint, Brooklyn", "mexican"),
    (24, "Dim Sum Harbor", 1114, -73.8214, 40.7131, "Murray Hill, Queens", "chinese"),
    (25, "Little Napoli To Go", 1115, -74.0055, 40.7282, "West Village, Manhattan", "italian"),
    (26, "Quindío Bandeja Bar", 1116, -73.9047, 40.7614, "Woodside, Queens", "colombian"),
    (27, "Coyoacán Corner", 1117, -73.9819, 40.6710, "Park Slope, Brooklyn", "mexican"),
    (28, "Hunan Heat Bowl", 1118, -73.8455, 40.7232, "Elmhurst, Queens", "chinese"),
    (29, "Trastevere Roma Pizza", 1119, -73.9897, 40.7505, "Garment District, Manhattan", "italian"),
    (30, "Salento Coffee Arepas", 1120, -73.9558, 40.6783, "Fort Greene, Brooklyn", "colombian"),
    (31, "Veracruz Fish Tacos", 1121, -74.0036, 40.7420, "Chelsea, Manhattan", "mexican"),
    (32, "Xi’an Spice Cart", 1122, -73.8810, 40.7006, "Richmond Hill, Queens", "chinese"),
    (33, "Sicily Hero House", 1123, -73.9962, 40.6263, "Bay Ridge, Brooklyn", "italian"),
    (34, "Cali Pollo Asado", 1124, -74.0776, 40.6445, "St. George, Staten Island", "colombian"),
    (35, "Puebla Birria Window", 1125, -74.0237, 40.7795, "Union City, NJ", "mexican"),
]


def esc(s: str) -> str:
    return s.replace("'", "''")


def main() -> None:
    lines: list[str] = [
        "-- Generated by scripts/generate_nyc_seed_100.py",
        "-- 100 flash deals, media_url always NULL (no images). Run AFTER migrate.sql.",
        "",
        "BEGIN;",
        "",
    ]

    lines.append("INSERT INTO vendors (id, name, phone, location, business_hours, status)")
    lines.append("VALUES")
    vrows = []
    for idx, name, ph4, lng, lat, _area, _cu in VENDORS:
        vid = f"v_seed_nyc_{idx:02d}"
        phone = f"+1718555{ph4}"
        vrows.append(
            f"  ('{vid}', '{esc(name)}', '{phone}', "
            f"ST_SetSRID(ST_MakePoint({lng}, {lat}), 4326)::geography, 'Daily 11a–10p', 'active')"
        )
    lines.append(",\n".join(vrows))
    lines.append("ON CONFLICT (phone) DO NOTHING;")
    lines.append("")

    deal_lines: list[str] = []
    deal_num = 31
    for vidx, _name, _ph4, lng, lat, _area, cuisine in VENDORS:
        vid = f"v_seed_nyc_{vidx:02d}"
        items = ITEMS[cuisine]
        for i in range(4):
            item_name, orig, dealp = items[i]
            fid = f"fd_seed_nyc_{deal_num:03d}"
            deal_num += 1
            qty = 18 + (deal_num % 12)
            deal_lines.append(
                f"  ('{fid}', '{vid}', '{esc(item_name)}', {orig:.2f}, {dealp:.2f}, NULL, "
                f"{qty}, {qty}, NOW(), NOW() + INTERVAL '7 days', 'active', 10, NULL, "
                f"ST_SetSRID(ST_MakePoint({lng}, {lat}), 4326)::geography)"
            )

    lines.append(
        "INSERT INTO flash_deals (\n"
        "  id, vendor_id, item_name, original_price, deal_price, discount_pct,\n"
        "  remaining_quantity, total_quantity, start_at, end_at, status, radius_miles, media_url, location\n"
        ") VALUES"
    )
    lines.append(",\n".join(deal_lines))
    lines.append("ON CONFLICT (id) DO NOTHING;")
    lines.append("")
    lines.append("COMMIT;")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(VENDORS)} vendors, {deal_num - 31} deals)")


if __name__ == "__main__":
    main()
